### ISSUE TITLE
Change legend in plots to reflect the model name used in the header of CSV files

### ISSUE THREAD

**Issue by c-h-david** [c-h-david/rrr#5]
@kandread, would you be able to implement this modification?

**Comment by kandread** [comment]
Of course!

**Comment by c-h-david** [comment]
Wonderful, thanks much!

**Comment by kandread** [comment]
Should we also grab the observation name from the CSV file? Here's an example using the code from kandread/rrr@afa20ee4a01932ac76a493e9c769de710a9f1f26:
[hydrograph_21434295.pdf](https://github.com/c-h-david/rrr/files/1475426/hydrograph_21434295.pdf)
