### ISSUE TITLE
rrr_cat_tot_gen_one_nhdplus.py DbfError

### ISSUE THREAD

**Issue by elyssac02** [c-h-david/rrr#9]
I have installed rrr and rapid with docker (on a Windows 10 computer) and am trying to prepare input files. Specifically, I'm trying to prepare the csv file from an NHDPlus catchment file using rrr_cat_tot_gen_one_nhdplus.py. I copied the files from my local computer to the docker container using the following commands:

```
# HUC10_catch = catchment shapefile
docker cp HUC10_catch.dbf <container ID>:/home/rrr/src/HUC10_catch.dbf
docker cp HUC10_catch.shp <container ID>:/home/rrr/src/HUC10_catch.shp
docker cp HUC10_catch.shx <container ID>:/home/rrr/src/HUC10_catch.shx
```

Next, I tried running the the rrr_cat_tot_gen_one_nhdplus python script using the following command:

```
docker exec <container ID> python /home/rrr/src/rrr_cat_tot_gen_one_nhdplus.py /home/rrr/src/HUC10_catch.dbf /home/rrr/src/rapid_catchment_HUC10.csv
```

And the following error is thrown:
```
Traceback (most recent call last):
  File "/home/rrr/src/rrr_cat_tot_gen_one_nhdplus.py", line 74, in <module>
    nhd_cat_dbf=dbf.Table(nhd_cat_file)
  File "/usr/local/lib/python2.7/dist-packages/dbf/ver_2.py", line 4870, in __new__
Command line inputs
- /home/rrr/src/HUC10_catch.dbf
- /home/rrr/src/rapid_catchment_HUC10.csv
Read shapefile
- Read attributes
    possibles = guess_table_type(filename)
  File "/usr/local/lib/python2.7/dist-packages/dbf/ver_2.py", line 8052, in guess_table_type
    reported = table_type(filename)
  File "/usr/local/lib/python2.7/dist-packages/dbf/ver_2.py", line 8081, in table_type
    raise DbfError("Unknown dbf type: %s (%x)" % (version, ord(version)))
dbf.ver_2.DbfError: Unknown dbf type:   (0)
```

I looked at the [table_type documentation](https://pythonhosted.org/dbf/dbf-pysrc.html#table_type) and the [version_map documentation](https://pythonhosted.org/dbf/dbf-module.html#version_map) and discovered that it seems to not be recognizing the dbf version correctly, therefore throwing the DbfError. In order to debug locally, I created a conda environment on my computer to run the `dbf.Table(nhd_cat_file)` command, which did not throw any errors. In addition, when I run the following code in the conda environment, it seems that the dbf file version matches one of the versions in the version_map documentation.

```
>> fd = open('HUC10_catch.dbf')
>> version = fd.read(1)
>> version
'\x03'
```

Any idea why the issue seems to only exist in the docker container? I am new to using docker, so please let me know if I'm doing something wrong.

Thanks!

**Comment by c-h-david** [comment]
I have to say I'm not really sure what's going on here, unfortunately.  I do most of my development on a virtual machine running Ubuntu Linux 16.04.1 LTS and only taught myself enough Docker to build the Docker images. When I run RRR on Docker, I usually do so interactively from inside the container, through `docker run --rm -it chdavid/rrr:v1.1.0` for example. You then have complete debugging capabilities.  If you need access to some files that are in your Windows machine, you may want to try to map volumes before running the container interactively (using the `-v` flags, see examples at https://github.com/c-h-david/rrr/blob/master/Dockerfile). You might also want to confirm that the version of `dbf` that you have in your conda environment is the same that the container uses.  Perhaps even try to update `dbf` inside the container. It's possible that your dbf file differs from what I've used before from NHDPlus. You might also want to look inside the test scripts (see e.g. https://github.com/c-h-david/rrr/blob/master/tst/tst_pub_repr_Emery_etal_2020_JHM2.sh#L398). This one is run every time the code is updated, and the Docker image is not published unless all tests pass.
